export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE'

export const AUTH_GITHUB_REQUEST = 'AUTH_GITHUB_REQUEST'
export const AUTH_GITHUB_SUCCESS = 'AUTH_GITHUB_SUCCESS'

export const PROFILE_GITHUB_REQUEST = 'PROFILE_GITHUB_REQUEST'
export const PROFILE_GITHUB_SUCCESS = 'PROFILE_GITHUB_SUCCESS'
export const PROFILE_GITHUB_FAILURE = 'PROFILE_GITHUB_FAILURE'
